# Advent of Code 2023
# Written by Dylan Celius

import datetime
import days

# Main
if __name__ == '__main__':
    print('Advent of Code 2023')
    timestamp = datetime.datetime.now()
    days.puzzle1()
    print('Puzzle 1 Complete!')
    days.puzzle2() 
    print('Puzzle 2 Complete!')
    days.puzzle3()
    print('Puzzle 3 Complete!')
    days.puzzle4()
    print('Puzzle 4 Complete!')
    days.puzzle5()
    print('Puzzle 5 Complete!')
    days.puzzle6()
    print('Puzzle 6 Complete!')
    days.puzzle7()
    print('Puzzle 7 Complete!')
    days.puzzle8()
    print('Puzzle 8 Complete!')
    days.puzzle9()
    print('Puzzle 9 Complete!')
    days.puzzle10()
    print('Puzzle 10 Complete!')
    days.puzzle11()
    print('Puzzle 11 Complete!')
    days.puzzle12()
    print('Puzzle 12 Complete!')
    days.puzzle13()
    print('Puzzle 13 Complete!')
    days.puzzle14()
    print('Puzzle 14 Complete!')
    days.puzzle15()
    print('Puzzle 15 Complete!')
    days.puzzle16()
    print('Puzzle 16 Complete!')
    days.puzzle17()
    print('Puzzle 17 Complete!')
    days.puzzle18()
    print('Puzzle 18 Complete!')
    days.puzzle19()
    print('Puzzle 19 Complete!')
    days.puzzle20()
    print('Puzzle 20 Complete!')
    days.puzzle21()
    print('Puzzle 21 Complete!')
    days.puzzle22()
    print('Puzzle 22 Complete!')
    days.puzzle23()
    print('Puzzle 23 Complete!')
    #days.puzzle24()
    #print('Puzzle 24 Complete!')
    #days.puzzle25()
    #print('Puzzle 25 Complete!')

    print('Total Time Elapsed: ', datetime.datetime.now() - timestamp)
